pipeline {
  agent{
    docker{
      image 'maven:3.6.1-jdk-8-slim'
      args '-v $HOME/.m2:/root/.m2'
    }
  }

  tools{
    maven 'maven 3.6.1'
  }
  stages{
    stage("build"){
      steps{
        echo 'Compiling worker app'
        dir('worker'){
          sh 'mvn compile'
        }
      }
    }
    stage("test"){
      steps{
        echo 'Running Unit Tets on worker app'
      }
    }
    stage("package"){
      steps{
        echo 'Packaging worker app'
      }
    }
  }
  post{
    always{
      echo 'Building multibranch pipeline for worker is completed..'}
    }
    failure {
      slackSend (channel: "instavoteg2", message: "Build Failed - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
    }
    success {
      slackSend (channel: "instavoteg2", message: "Build Succeeded - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
    }
  }
